### ISSUE TITLE
Can't enable the tool in Blender 4.1

### ISSUE THREAD

**Issue by JolinVTF** [MMD-Blender/blender_mmd_tools#153]
Blender: 4.1
mmd_tools: v4.1.0
OS: Window 11

First time using this tool. I can't enable the mmd tool in blender. 
![1](https://github.com/UuuNyaa/blender_mmd_tools/assets/165877456/7975cc59-6019-4372-8dc5-e2e117e5e4d9)

If I try to enable it, it will pop up this the preference window. Not sure what happen T^T
![2](https://github.com/UuuNyaa/blender_mmd_tools/assets/165877456/4beb60ef-384a-415c-8d28-270e7111c67b)

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\addon_utils.py", line 353, in enable
    importlib.reload(mod)
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\python\Lib\importlib\__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 621, in _exec
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\favou\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\mmd_tools\__init__.py", line 22, in <module>
    auto_load.init()
  File "C:\Users\favou\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\mmd_tools\auto_load.py", line 25, in init
    modules = get_all_submodules(Path(__file__).parent)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\favou\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\mmd_tools\auto_load.py", line 53, in get_all_submodules
    return list(iter_submodules(directory, directory.name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\favou\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\mmd_tools\auto_load.py", line 57, in iter_submodules
    yield importlib.import_module("." + name, package_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\favou\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\mmd_tools\core\translations.py", line 10, in <module>
    from mmd_tools.core.model import FnModel, Model
ImportError: cannot import name 'FnModel' from 'mmd_tools.core.model' (C:\Users\favou\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\mmd_tools\core\model.py)

**Comment by lsitvoid** [comment]
我不知道，但是我在使用3.0.0版本时也遇到此问题。
Traceback (most recent call last):
  File "G:\blender-3.0.0-windows-x64\blender-3.0.0-windows-x64\3.0\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\shengming\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\mmd_uuunyaa_tools\__init__.py", line 60, in <module>
    auto_load.init()
  File "C:\Users\shengming\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\mmd_uuunyaa_tools\auto_load.py", line 25, in init
    modules = get_all_submodules(Path(__file__).parent)
  File "C:\Users\shengming\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\mmd_uuunyaa_tools\auto_load.py", line 53, in get_all_submodules
    return list(iter_submodules(directory, directory.name))
  File "C:\Users\shengming\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\mmd_uuunyaa_tools\auto_load.py", line 57, in iter_submodules
    yield importlib.import_module("." + name, package_name)
  File "G:\blender-3.0.0-windows-x64\blender-3.0.0-windows-x64\3.0\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\shengming\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\mmd_uuunyaa_tools\asset_search\cache.py", line 362
    match content.state:
          ^
SyntaxError: invalid syntax

**Comment by Takuyax** [comment]
I can confirm this problem on Kubuntu 23.10 (yes, I need to upgrade), using Blender 4.1.1 and the latest mmd_tools 4.1 release.

Traceback (most recent call last):
  File "/home/user/blender-4.1.1-linux-x64/4.1/scripts/modules/addon_utils.py", line 376, in enable
    mod = importlib.import_module(module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/blender-4.1.1-linux-x64/4.1/python/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/user/.config/blender/4.1/scripts/addons/mmd_tools/__init__.py", line 44, in <module>
    auto_load.init()
  File "/home/user/.config/blender/4.1/scripts/addons/mmd_tools/auto_load.py", line 25, in init
    modules = get_all_submodules(Path(__file__).parent)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.config/blender/4.1/scripts/addons/mmd_tools/auto_load.py", line 53, in get_all_submodules
    return list(iter_submodules(directory, directory.name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.config/blender/4.1/scripts/addons/mmd_tools/auto_load.py", line 57, in iter_submodules
    yield importlib.import_module("." + name, package_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/blender-4.1.1-linux-x64/4.1/python/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/user/.config/blender/4.1/scripts/addons/mmd_tools/core/translations.py", line 13, in <module>
    from mmd_tools.core.model import FnModel, Model
ImportError: cannot import name 'FnModel' from 'mmd_tools.core.model' (/home/user/.config/blender/4.1/scripts/addons/mmd_tools/core/model.py)

**Comment by qwertyuiop1923** [comment]
same

**Comment by KURAMAAA0** [comment]
Same, happens with both version 4.0.0 and 4.1.0
I'm using Goo Engine (Blender 4.1)
`Traceback (most recent call last):
  File "C:\blender-git\build_windows_x64_vc17_Release\bin\Release\4.1\scripts\modules\addon_utils.py", line 365, in enable
    mod = importlib.import_module(module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\blender-git\build_windows_x64_vc17_Release\bin\Release\4.1\python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\noman\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\mmd_tools\__init__.py", line 44, in <module>
    auto_load.init()
  File "C:\Users\noman\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\mmd_tools\auto_load.py", line 25, in init
    modules = get_all_submodules(Path(__file__).parent)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\noman\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\mmd_tools\auto_load.py", line 53, in get_all_submodules
    return list(iter_submodules(directory, directory.name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\noman\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\mmd_tools\auto_load.py", line 57, in iter_submodules
    yield importlib.import_module("." + name, package_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\blender-git\build_windows_x64_vc17_Release\bin\Release\4.1\python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\noman\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\mmd_tools\properties\pose_bone.py", line 9, in <module>
    from mmd_tools.properties import patch_library_overridable
ImportError: cannot import name 'patch_library_overridable' from 'mmd_tools.properties' (C:\Users\noman\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\mmd_tools\properties\__init__.py)

`

**Comment by danya0123** [comment]
You can try using a tool like mikumikuconvert.com to first convert pmx to fbx and then import the fbx file into blender.
