### ISSUE TITLE
Changes in Bone Targeting During Model Import/Export

### ISSUE THREAD

**Issue by kafeijk** [MMD-Blender/blender_mmd_tools#156]
- Blender 3.6
 - mmd_tools v2.10.2
 - Windows 11

I added an 'upper body2' bone to a model without a sub-standard bone (such as the MIKU model from early MMD). After importing the modified model into Blender and then exporting it, I checked it in PmxEditor. Previously, the 'upper body' bone targeted 'upper body2,' but now it has changed to a relative position.
before:
![image](https://github.com/UuuNyaa/blender_mmd_tools/assets/49871777/c84b6c80-edd1-4de2-ba02-6b18608fd96d)

after:
![无标题](https://github.com/UuuNyaa/blender_mmd_tools/assets/49871777/fefcbd4f-de65-4d60-a1c4-dba423ffb088)

When importing the model, the head and tail are checked using EditBone, but it's not the EditBone type here.
https://github.com/UuuNyaa/blender_mmd_tools/blob/d148bdbd520a0ddb2ffd0389a0217a297ad107f0/mmd_tools/core/pmx/exporter.py#L407C29-L407C83
 I'm not sure if the current situation is due to the code or if the file structure is inherently like this.

**Comment by kafeijk** [comment]
Additionally, if the target changes, the local axes in MMD will also change accordingly.
before:
![无标题](https://github.com/UuuNyaa/blender_mmd_tools/assets/49871777/4f3bc455-1304-414a-8801-e9bb49455e73)
after:
![无标题2](https://github.com/UuuNyaa/blender_mmd_tools/assets/49871777/2f62f739-7f55-4a8b-9a03-4cf1981eb14f)

**Comment by rintrint** [comment]
I am trying to figure this out. The related old issue and commit are #100 and bc02663.

**Comment by rintrint** [comment]
The test_pmx_exporter.py script can also demonstrate the issue.
```
C:\Users\user\Desktop>blender --background -noaudio --python tests/test_pmx_exporter.py -- --verbose
Blender 4.2.7 LTS (hash f12c49eec802 built 2025-02-18 09:55:07)
Reloading external rigs...
Reloading external metarigs...
test_pmx_exporter (__main__.TestPmxExporter.test_pmx_exporter) ...
    Check: {'DISPLAY', 'MESH', 'PHYSICS', 'ARMATURE', 'MORPHS'} | Import: {'ARMATURE', 'MORPHS', 'PHYSICS', 'DISPLAY', 'MESH'}

     -  1/1 | filepath: C:\Users\user\Desktop\samples\pmx\[Reverse1999]_Sonetto_Basic.pmx
Info: Exported MMD model "[Reverse1999] Sonetto Basic" to "C:\Users\user\Desktop\tests\output\0.pmx"
FAIL

======================================================================
FAIL: test_pmx_exporter (__main__.TestPmxExporter.test_pmx_exporter)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\user\Desktop\tests\test_pmx_exporter.py", line 654, in test_pmx_exporter
    self.__check_pmx_bones(source_model, result_model)
  File "C:\Users\user\Desktop\tests\test_pmx_exporter.py", line 302, in __check_pmx_bones
    self.assertEqual(displayConnection0, displayConnection1, msg)
AssertionError: '上半身2' != (0.0, 1.3766803741455078, -0.004888296127319336) : 上半身

----------------------------------------------------------------------
Ran 1 test in 7.346s

FAILED (failures=1)
```

**Comment by rintrint** [comment]
This could easily be solved by saving the Bone Target.

Also, allow users to edit the Bone Target as well.

**Comment by rintrint** [comment]
Closed as fixed.
