### ISSUE TITLE
Traceback error upon PMX model import attempt

### ISSUE THREAD

**Issue by AnthonyZDavis** [MMD-Blender/blender_mmd_tools#167]
- **Blender:** 4.1
- **MMD Tools:** 4.0.0
- **OS:** Windows 11

1. Go to **MMD Tools**
2. Scroll down to **Scene Setup**
3. Click on **Model > Import**
4. Select model to import
5. See error below
6. See screenshot below for uploaded model

**Reported error:**
> Traceback (most recent call last):
>   File "C:\Users\a####\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\mmd_tools\operators\fileio.py", line 168, in execute
>   File "C:\Users\a####\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\mmd_tools\operators\fileio.py", line 187, in _do_execute
>     handler = log_handler(self.log_level, filepath=self.filepath + ".mmd_tools.import.log")
>   File "C:\Users\a####\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\mmd_tools\core\pmd\importer.py", line 21, in execute
>     importer = import_pmx.PMXImporter()
>     ^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\a####\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\mmd_tools\core\pmx\importer.py", line 851, in execute
>     _PMXCleaner.clean(self.__model, "MORPHS" not in types)
>     ^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\a####\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\mmd_tools\core\pmx\importer.py", line 555, in __importMaterials
>     mmd_mat.enabled_toon_edge = i.enabled_toon_edge
>                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\a####\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\mmd_tools\core\material.py", line 465, in create_texture
>     mmd_material.is_double_sided = not m.game_settings.use_backface_culling
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\a####\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\mmd_tools\core\material.py", line 565, in __create_texture_node
>     vec_trans.convert_to = "CAMERA"
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\a####\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\mmd_tools\core\material.py", line 769, in __update_shader_nodes
> KeyError: 'bpy_prop_collection[key]: key "Shader" not found'

![image](https://github.com/user-attachments/assets/5d0125e6-e4cc-46f3-8b17-4793db03cee6)

**Comment by rintrint** [comment]
You can try the below version combination:
Blender 4.1 with MMD Tools 4.1.0
Blender 4.2 with MMD Tools 4.2.2

MMD Tools 4.0.0 is not the latest for Blender 4.1, please try MMD Tools 4.1.0.
Or go for 4.2.
