### ISSUE TITLE
Use Blender link features in mmd model cause a lot of error and lag.

### ISSUE THREAD

**Issue by PaulsonH** [MMD-Blender/blender_mmd_tools#176]
I link my MMD model from file scenes to other scenes, But it keeps on showing thousands of errors in CMD like below

I turn off the MMD tool addon, the error will disappear.

It will show those error many times based on how many physical bone in your mmd model.
![image](https://github.com/user-attachments/assets/4c940752-5a5f-4e02-be73-6ccbc68603dc)
![image](https://github.com/user-attachments/assets/ef09515e-b274-4eda-9f0b-272859de6e55)

Traceback (most recent call last):
AttributeError: 'Context' object has no attribute 'active_object'
File "C:\Users\74091\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\mmd_tools\bpyutils.py", line 315, in get_active_object
File "C:\Users\74091\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\mmd_tools\bpyutils.py", line 315, in get_active_object
File "C:\Users\74091\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\mmd_tools\properties\root.py", line 195, in _getActiveJointObject
File "C:\Users\74091\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\mmd_tools\properties\root.py", line 178, in _getActiveRigidbodyObject
AttributeError: 'Context' object has no attribute 'active_object'
File "C:\Users\74091\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\mmd_tools\properties\root.py", line 193, in _getActiveJointObject
AttributeError: 'Context' object has no attribute 'active_object'
File "C:\Users\74091\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\mmd_tools\properties\root.py", line 178, in _getActiveRigidbodyObject
Traceback (most recent call last):
return context.active_object
active_obj = FnContext.get_active_object(context)
Traceback (most recent call last):
File "C:\Users\74091\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\mmd_tools\properties\root.py", line 195, in _getActiveJointObject
^^^^^^^^^^^^^^^^^^^^^
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\74091\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\mmd_tools\properties\root.py", line 180, in _getActiveRigidbodyObject
return context.active_object
Traceback (most recent call last):
active_obj = FnContext.get_active_object(context)
AttributeError: 'Context' object has no attribute 'active_object'
File "C:\Users\74091\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\mmd_tools\properties\root.py", line 220, in _getActiveMeshObject
File "C:\Users\74091\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\mmd_tools\bpyutils.py", line 315, in get_active_object
WARNING:root:Object.select is deprecated since v4.0.0: Use Object.select_get() method instead
Stack (most recent call last):
File "C:\Users\74091\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\mmd_tools\properties\root.py", line 499, in __get_select
utils.warn_deprecation("Object.select", "v4.0.0", "Use Object.select_get() method instead")
^^^^^^^^^^^^^^^^^^^^^
Traceback (most recent call last):
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
active_obj = FnContext.get_active_object(context)
File "C:\Users\74091\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\mmd_tools\properties\root.py", line 222, in _getActiveMeshObject
return context.active_object
WARNING:root:Object.select is deprecated since v4.0.0: Use Object.select_get() method instead
Stack (most recent call last):
File "C:\Users\74091\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\mmd_tools\properties\root.py", line 499, in __get_select
utils.warn_deprecation("Object.select", "v4.0.0", "Use Object.select_get() method instead")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\74091\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\mmd_tools\bpyutils.py", line 315, in get_active_object
AttributeError: 'Context' object has no attribute 'active_object'
File "C:\Users\74091\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\mmd_tools\properties\root.py", line 220, in _getActiveMeshObject
File "C:\Users\74091\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\mmd_tools\bpyutils.py", line 315, in get_active_object
active_obj = FnContext.get_active_object(context)
^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\74091\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\mmd_tools\properties\root.py", line 222, in _getActiveMeshObject
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
return context.active_object
return context.active_object
File "C:\Users\74091\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\mmd_tools\bpyutils.py", line 315, in get_active_object
active_obj = FnContext.get_active_object(context)
WARNING:root:Object.hide is deprecated since v4.0.0: Use Object.hide_get() method instead
Stack (most recent call last):
File "C:\Users\74091\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\mmd_tools\properties\root.py", line 509, in __get_hide
utils.warn_deprecation("Object.hide", "v4.0.0", "Use Object.hide_get() method instead")
AttributeError: 'Context' object has no attribute 'active_object'
File "C:\Users\74091\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\mmd_tools\properties\root.py", line 193, in _getActiveJointObject
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^^^^^^^^^^^^^^^^^^^
return context.active_object
File "C:\Users\74091\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\mmd_tools\bpyutils.py", line 315, in get_active_object
WARNING:root:Object.hide is deprecated since v4.0.0: Use Object.hide_get() method instead
Stack (most recent call last):
File "C:\Users\74091\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\mmd_tools\properties\root.py", line 509, in __get_hide
utils.warn_deprecation("Object.hide", "v4.0.0", "Use Object.hide_get() method instead")
Traceback (most recent call last):
^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Context' object has no attribute 'active_object'
File "C:\Users\74091\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\mmd_tools\properties\root.py", line 178, in _getActiveRigidbodyObject
File "C:\Users\74091\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\mmd_tools\properties\root.py", line 222, in _getActiveMeshObject
AttributeError: 'Context' object has no attribute 'active_object'
File "C:\Users\74091\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\mmd_tools\properties\root.py", line 193, in _getActiveJointObject
^^^^^^^^^^^^^^^^^^^^^
Traceback (most recent call last):
active_obj = FnContext.get_active_object(context)
Traceback (most recent call last):
AttributeError: 'Context' object has no attribute 'active_object'
File "C:\Users\74091\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\mmd_tools\properties\root.py", line 180, in _getActiveRigidbodyObject
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\74091\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\mmd_tools\properties\root.py", line 195, in _getActiveJointObject
File "C:\Users\74091\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\mmd_tools\properties\root.py", line 220, in _getActiveMeshObject
Traceback (most recent call last):
File "C:\Users\74091\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\mmd_tools\bpyutils.py", line 315, in get_active_object
active_obj = FnContext.get_active_object(context)

**Comment by FhyTan** [comment]
I encounter this same error.

**Comment by rintrint** [comment]
utils.warn_deprecation can be ignored since it's just a warning.
I've already changed utils.warn_deprecation warnings to TODO list items in the latest main branch, because the numerous warnings were severely affecting console usability. (a084667)

The key issue is AttributeError: 'Context' object has no attribute 'active_object'.
I tried using the link functionality but didn't encounter the error in the latest main branch version.
I'd like to ask how you're using the link to functionality - how are you linking the model? Are you placing the model in a collection and then linking the collection?
Could you test if the latest main branch still has the same problem? Thank you.

**Comment by PaulsonH** [comment]
I tested the new version, and it is still the same. I forgot to say that the utils.warn_deprecation will freeze the blender for several seconds.

Yes, I placed the model in a collection and then linked the collection. 

And physics is not working on the linking  model,

 I give you the file. Maybe you can test it.


https://drive.google.com/file/d/1cGRnTTiYCI3TgotDn4lKbz-BctSNfDxH/view?usp=drive_link

**Comment by rintrint** [comment]
Sorry I didn't make myself clear. You need to download this repo and copy the mmd_tools folder in it, rather than downloading the release version.

I remember that Blender's link functionality is very limited. Are you sure it supports physics? I recall that things imported through the link feature seem to be rather static and don't have full functionality.

**Comment by rintrint** [comment]
I cannot download the file. It says "You need access."

**Comment by PaulsonH** [comment]
I 

> I cannot download the file. It says "You need access."无法下载文件。提示“您需要访问权限。”

I give you the access

**Comment by rintrint** [comment]
I linked the collection, but nothing happened. How can I reproduce it?
<img width="1280" alt="Image" src="https://github.com/user-attachments/assets/b83816f0-c981-4a9e-b50d-fdd999986fae" />

**Comment by PaulsonH** [comment]
![Image](https://github.com/user-attachments/assets/fd323724-1283-4a9e-b2b9-484754d296ec)

**Comment by PaulsonH** [comment]
Well, the physics can work in link mode,

You need to turn on the original file with mmd physics, and save.

 Then you have to linked these three collection to new file , and Library override The first one

![Image](https://github.com/user-attachments/assets/b064e481-85c7-41a0-8ec8-f5aa0898f3c1)

And then set up the rigid world Manual  

![Image](https://github.com/user-attachments/assets/8921042c-aa6e-41aa-86c1-0269a71265c3)

Then the physics will work.

**Comment by nagadomi** [comment]
I haven't tested this issue, but it may be a similar problem as https://github.com/powroupi/blender_mmd_tools/pull/332

**Comment by rintrint** [comment]
Ok, I got the physics working. But why don't I need to library override **RigidBodyWorld** and **RigidBodyConstraints**?  

This is a quick fix for `bpyutils.py`, but I think I need to look into it.  
```python
    @staticmethod
    def get_active_object(context: bpy.types.Context) -> Optional[bpy.types.Object]:
        if hasattr(context, 'active_object'):
            return context.active_object
        return None
```

It looks like mmd_tools was not designed with this use case in mind, so some defensive programming needs to be added.

**Comment by PaulsonH** [comment]
> Ok, I got the physics working. But why don't I need to library override **RigidBodyWorld** and **RigidBodyConstraints**?
> 
> This is a quick fix for `bpyutils.py`, but I think I need to look into it.
> 
>     @staticmethod
>     def get_active_object(context: bpy.types.Context) -> Optional[bpy.types.Object]:
>         if hasattr(context, 'active_object'):
>             return context.active_object
>         return None
> It looks like mmd_tools was not designed with this use case in mind, so some defensive programming needs to be added.

Because it is already override the in the origin model. And they are in the same collection. 
But there is still has a problem , if there has multiple character it will not working well,.q maybe I need to make them local and then put them in the same collection 1

**Comment by rintrint** [comment]
Why won't they work well? If you link them from the same file, they should use the same RigidBodyWorld and RigidBodyConstraints, shouldn't they?

Currently, I think I should add some minor defensive programming, but not everywhere in mmd_tools. I also noticed that many buttons need to be disabled when the selected MMD model is a linked library override model.

**Comment by rintrint** [comment]
I wonder if there is a global poll method that disables MMD tool panels when linked or library override objects are selected.

**Comment by PaulsonH** [comment]
> Why won't they work well? If you link them from the same file, they should use the same RigidBodyWorld and RigidBodyConstraints, shouldn't they?
> 
> Currently, I think I should add some minor defensive programming, but not everywhere in mmd_tools. I also noticed that many buttons need to be disabled when the selected MMD model is a linked library override model.

Well, Because you are linked rigidbody Collection from the first file, the linked collection is not able to edit it. 

Then when you want to link another collection from another file.

It will automatically Rename it to rigidbodyWorld .001 and RigidBodyConstraints.001 etc. and Physics will not work on this character.

But I think there has the solution is just to put those character files in the same original file. Then link them. And they will be in the same rigid world.

**Comment by rintrint** [comment]
Closing as fixed. While I'm not entirely sure whether Blender itself has fully reliable link and library override features, this particular issue has been resolved.
